version: "2"
services:
   mysql:
     image: "mysql:5.5"
     hostname: "mysqlserver"
     container_name: "mysql"
     ports: 
       - "3306:3306"
     volumes:
       - $MYSQL_DATADIR:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=aloja123

   simple:
     image: "egob/simple:v1.6"
     container_name: "simple"
     hostname: "simple"
     ports:
       - "9000:9000"
     volumes:
       - $WEBROOT:$INTERNAL_PATH
     links:
       - mysql:simple-db 
     tty: true

   nginx:
     image: "nginx"
     container_name: "nginx"
     hostname: "nginx-server"
     ports:
       - "80:80"
     volumes:
       - $WEBROOT:$INTERNAL_PATH:ro
       - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro 
     links:
       - simple
     depends_on:
       - simple
