version: "3.1"
services:
   simple:
     image: "arkhotech/php-fpm5.6"
     hostname: "simple.arkhotech.space"
     volumes:
       - /home/ubuntu/SIMPLE:/var/www/html
     tty: true
     cap_add:
       - SYS_PTRACE
     networks:
       - simple_nw 
   nginx:
     image: "nginx"
     hostname: "nginx-server"
     ports:
       - "80:80"
     volumes:
       - /home/ubuntu/SIMPLE:/var/www/html:ro
       - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro 
     depends_on:
       - simple
     networks:
       - simple_nw 
   simple-db:
     image: "mysql:5.5"
     volumes:
       - /home/ubuntu/data:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       - MYSQL_ROOT_PASSWORD=simple123
     networks:
       - simple_nw

networks:
   simple_nw:
     driver: overlay 
