version: "3.1"
services:
   simple:
     image: "egob/simple:v1.6"
     hostname: "simple"
     ports:
       - "9000:9000"
     volumes:
       - /home/ubuntu/SIMPLE:/var/www/html
     links:
       - mysql:simple-db 
     tty: true
     networks:
       - back
   nginx:
     image: "nginx"
     hostname: "nginx-server"
     ports:
       - "80:80"
     volumes:
       - /home/ubuntu/SIMPLE:/var/www/html:ro
       - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro 
     links:
       - simple
     depends_on:
       - simple
     networks:
       - front
       - back 
networks:
  
   front:
     driver: overlay 
   back:
     driver: overlay 
