alfresco:
  environment:
    CONTENT_STORE: /content
    DB_HOST: postgresql
    DB_KIND: postgresql
    DB_NAME: alfresco
    DB_PASSWORD: alfresco
    DB_USERNAME: alfresco
    #LDAP_AUTH_USERNAMEFORMAT: uid=%s,cn=users,cn=accounts,dc=example,dc=com
    #LDAP_DEFAULT_ADMINS: admin
    #LDAP_ENABLED: true
    #LDAP_GROUP_SEARCHBASE: cn=groups,cn=accounts,dc=example,dc=com
    #LDAP_SECURITY_CREDENTIALS: secret
    #LDAP_SECURITY_PRINCIPAL: uid=admin,cn=users,cn=accounts,dc=example,dc=com
    #LDAP_URL: ldap://ipa.example.com:389
    #LDAP_USER_SEARCHBASE: cn=users,cn=accounts,dc=example,dc=com
  build: .
  links:
    - postgresql:postgresql
  ports:
    - "21:21"
    - "137:137"
    - "138:138"
    - "139:139"
    - "445:445"
    - "7070:7070"
    - "8009:8009"
    - "8080:8080"
  volumes:
    - /alfresco/alf_data
    - /alfresco/tomcat/logs
    - /content

postgresql:
  environment:
    POSTGRES_DB: alfresco
    POSTGRES_PASSWORD: alfresco
    POSTGRES_USER: alfresco
  image: postgres:9.4
  volumes:
    - /var/lib/postgresql/data
