version: "3.1"

services:
   simple:
     image: "registry.arkhotech.space/simple"
     hostname: "simple.arkhotech.space"
     deploy:
       mode: global
     tty: true
     networks:
       - backend 
     build:
       context: .
       dockerfile: simple-dockerfile
   nginx:
     image: "registry.arkhotech.space/nginx"
     hostname: "nginx-server"
     deploy:
       mode: global
     ports:
       - "80:80"
     volumes:
       - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro 
     depends_on:
       - simple
     networks:
       - frontend
       - backend 
     build:
       context: . 
       dockerfile: nginx-dockerfile
   database:
     image: "mysql:5.5"
     volumes:
       -  /home/simple/data:/var/lib/mysql
       - ./assets/installdb.sh:/installdb.sh
       - ./assets/init.sh:/init.sh:ro
       -  /home/simple/SIMPLE/sql:/sql
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=simple123
     networks:
       - backend
     deploy:
       replicas: 1
       placement:
         constraints: 
           - node.role == manager

networks:
   backend:
     driver: overlay
   frontend:
     driver: overlay
