version: "3.1"

services:
   simple:
     image: "registry.arkhotech.space/simple:3"
     deploy:
       placement: 
          constraints: [node.role == manager ]
     tty: true
     volumes:
       - ./SIMPLE:/var/www/html
       - ./assets/php.ini:/etc/php5/fpm/php.ini:ro
       - ./assets/ssmtp.conf:/etc/ssmtp/ssmtp.conf
       - ./assets/revaliases:/etc/ssmtp/revaliases
       - ./assets/ssmtp.conf:/usr/local/etc/php/conf.d/mail.ini
     networks:
       - backend 
     build:
       context: .
       dockerfile: simple-dockerfile
   nginx:
     image: "registry.arkhotech.space/nginx"
     hostname: "nginx-server"
     deploy:
       placement:
          constraints: [node.role == manager]
     ports:
       - "80:80"
     volumes:
       - ./SIMPLE:/var/www/html
     depends_on:
       - simple
     networks:
       - frontend
       - backend 
     build:
       context: . 
       dockerfile: nginx-dockerfile
   database:
     image: "mysql:5.5"
     volumes:
       -  simple-mysql:/var/lib/mysql
       - ./assets/installdb.sh:/installdb.sh
       - ./assets/init.sh:/init.sh:ro
       -  ./SIMPLE/sql:/sql
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=simple123
     networks:
       - backend
     deploy:
       replicas: 1
       placement:
         constraints: 
           - node.role == manager

volumes:
   codigo:
   simple-mysql:
networks:
   backend:
     driver: overlay
   frontend:
     driver: overlay
