version: "3.1"

services:
   simple:
     image: "registry.arkhotech.space/simple"
     hostname: "simple.arkhotech.space"
     deploy:
       placement: 
          constraints: [node.role == manager ]
     tty: true
     volumes:
       - codigo:/var/www/html
     networks:
       - backend 
     build:
       context: .
       dockerfile: simple-dockerfile
   nginx:
     image: "registry.arkhotech.space/nginx"
     hostname: "nginx-server"
     deploy:
       placement:
          constraints: [node.role == manager]
     ports:
       - "8090:80"
     volumes:
       - codigo:/var/www/html
     depends_on:
       - simple
     networks:
       - frontend
       - backend 
     build:
       context: . 
       dockerfile: nginx-dockerfile
   database:
     image: "mysql:5.5"
     volumes:
       -  database:/var/lib/mysql
       - ./assets/installdb.sh:/installdb.sh
       - ./assets/init.sh:/init.sh:ro
       -  /home/simple/SIMPLE/sql:/sql
     ports:
       - "3307:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=simple123
     networks:
       - backend
     deploy:
       replicas: 1
       placement:
         constraints: 
           - node.role == manager

volumes:
   codigo:
   database:
networks:
   backend:
     driver: overlay
   frontend:
     driver: overlay
